-- Generate a table iwht a sequence with primary key value which can be retrieved and specified or will fill in automatically if omitted
/* CREATE TABLE tbl1 (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text
) */
-- Database: postgres

-- CREATE DATABASE postgres
--     WITH
--     OWNER = postgres
--     ENCODING = 'UTF8'
--     LC_COLLATE = 'en_US.utf8'
--     LC_CTYPE = 'en_US.utf8'
--     TABLESPACE = pg_default
--     CONNECTION LIMIT = -1;

-- COMMENT ON DATABASE postgres
--     IS 'default administrative connection database';

-- CREATE SEQUENCE tbl2_id_seq;
--
-- ALTER SEQUENCE tbl2_id_seq
--     OWNER TO postgres;
-- Table: public.tbl2

CREATE TABLE public.tbl2
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    foreign_name text COLLATE pg_catalog."default",
    CONSTRAINT tlb2_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.tbl2
    OWNER to postgres;
-- Table: public.tbl1

CREATE TABLE public.tbl1
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    foreign_name integer,
    name text COLLATE pg_catalog."default",
    CONSTRAINT tbl1_pkey PRIMARY KEY (id),
    CONSTRAINT tbl1_foreign_name_fkey FOREIGN KEY (foreign_name)
        REFERENCES public.tbl2 (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public.tbl1
    OWNER to postgres;

